services:
  keycloak:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=kcadmin
      - DB_VENDOR=h2
      - KC_HTTP_PORT=8082
      - KC_HEALTH_ENABLED=true
    command:
      - "start-dev"
    ports:
      - "8082:8082"
